ministryofjustice/opg-paper-identity

- docker-compose.yml
Allow local installation of composer dependencies using docker
> Add composer mounts for local installs #patch

- Makefile
Update Make build with api-test
Fixes ###-####
> Update Make build with api-test

- service-front/module/Application/view/application/pages/donor_id_check.twig
- service-front/module/Application/view/application/pages/donor_id_check_with_table.twig
- service-front/module/Application/view/application/pages/how_will_the_donor_confirm.twig
> removing court of protection option

- service-api/module/Application/src/Controller/IdentityController.php
- service-api/module/Application/src/Nino/Validator.php
- service-api/module/Application/src/Nino/ValidatorInterface.php
- service-api/module/Application/test/Controller/IdentityControllerTest.php
> ID-100-Tidy-up-NINO-mock

- docker-compose.yml
- service-api/Dockerfile
- service-api/docker/php/memory_limit.ini
- service-api/docker/php/opcache.ini
- service-api/docker/php/www.conf
- service-front/Dockerfile
- service-front/docker/php/apcu.ini
> SP-2100 - Fix Container healthchecks, align PHP config, remove apcu #minor

- .github/workflows/build-scan.yml
- .github/workflows/workflow-main.yml
- Makefile
- docker-compose.yml
- docker/yoti/Dockerfile
Push Yoti Mock API for ephemeral env deployment
> ID-159 - Build & Push the Yoti Mock API Image #minor

- service-api/module/Application/src/Controller/IdentityController.php
- service-api/module/Application/src/Model/Entity/CaseData.php
`CaseData->toArray()` is not properly typed and allows for generic access/insertion. Instead, use the properties on CaseData directly.
Use the properties directly instead
> Remove CaseData->toArray()

- service-front/module/Application/view/application/pages/donor_id_check_with_table.twig
- service-front/module/Application/view/application/pages/driving_licence_number.twig
- service-front/module/Application/view/application/pages/driving_licence_number_fail.twig
- service-front/module/Application/view/application/pages/national_insurance_number.twig
- service-front/module/Application/view/application/pages/national_insurance_number_fail.twig
- service-front/module/Application/view/application/pages/passport_number.twig
- service-front/module/Application/view/application/pages/passport_number_fail.twig
> adding required data

- service-api/module/Application/src/Yoti/YotiService.php
> ID-197-Minor-Correct-Post-Office-Search-string-parameter

- service-front/module/Application/src/Services/SiriusApiService.php
- service-front/module/Application/test/Services/SiriusApiServicePactTest.php
To increase converage of the contract between the two services
Fixes #ID-173 #patch
> Add Pact test for Sirius's "get LPA" endpoint

- service-front/module/Application/view/application/pages/donor_lpa_check.twig
> ID-202 update title text on LPA page #patch

- docker-compose.yml
The latest version contains a bug that means it cannot run at all
#patch
> Fix Prism to 5.8.2

- service-front/module/Application/view/application/pages/cp/confirm_lpas.twig
- service-front/web/main.scss
> Bugfix/ID-223 cp flow fixes#patch

- service-api/module/Application/test/Controller/IdentityControllerTest.php
> ID-213-adding-tests-for-add-remove-lpa#minor

- service-front/module/Application/src/Controller/CPFlowController.php
- service-front/module/Application/src/Helpers/LpaFormHelper.php
- service-front/module/Application/test/Helpers/LpaFormHelperTest.php
- service-front/module/Application/view/application/pages/cp/add_lpa.twig
- service-front/web/main.scss
Fixes ###-####
* [x ] I have updated documentation where relevant
> Bugfix/id 224 fin lpa to add#patch

- service-front/module/Application/config/module.config.php
- service-front/module/Application/src/Controller/DonorPostOfficeFlowController.php
- service-front/module/Application/test/Controller/PostOfficeDonorFlowControllerTest.php
- service-front/module/Application/view/application/pages/post_office/choose_country.twig
- service-front/module/Application/view/application/pages/post_office/post_office_documents.twig
> ID-204 adding country choose. route#minor

- service-front/module/Application/view/application/pages/post_office/post_office_documents.twig
> ID-239 content fixes#patch

- service-front/module/Application/view/application/pages/cp/how_will_the_cp_confirm.twig
> ID-264 content changes#minor

- service-api/Dockerfile
ID-253 add soap extension to api Docker container.
> Add SOAP client to api container 

- service-api/module/Application/src/Module.php
API errors can be swallowed, making it hard to debug when problems occur.
For ID-195 #patch
> Always log API errors

- service-front/module/Application/view/application/pages/how_will_the_donor_confirm.twig
> ID-263-content-changes#minor

- service-front/module/Application/config/module.config.php
- service-front/module/Application/view/application/pages/cp/post_office_documents.twig
> ID-203 content changes#patch

- service-front/module/Application/view/application/pages/cp/post_office_documents.twig
- service-front/module/Application/view/application/pages/post_office/post_office_documents.twig
> ID-297 switching radios to po values#patch

- service-front/module/Application/src/Controller/CPFlowController.php
- service-front/module/Application/src/Helpers/FormProcessorHelper.php
- service-front/module/Application/test/Helpers/FormProcessorHelperTest.php
> ID-296 allow 2 digit years#minor

- docker/yoti/openapi.yml
- service-api/docker-compose.env
Branch look route was missing from both Yoti yml files which were merged to replace our old version.  Also need to append /idverify/v1 to routes
Fixes ###-####
> ID-308-Fix-Yoti-mock-for-branch-lookup

- docker/sirius/openapi.yml
- service-front/module/Application/src/Services/SiriusApiService.php
> ID-314-Add-missing-auth-header-for-Sirius-PDF-request

- service-front/module/Application/view/application/pages/post_office/confirm_post_office.twig
> ID-311 text change#patch

- service-api/module/Application/src/Controller/YotiController.php
- service-api/module/Application/src/Yoti/SessionStatusService.php
- service-api/module/Application/test/ApplicationTest/Services/SessionStatusServiceTest.php
…' key from array as not used anymore?
Fixes ###-####
> ID-312-Add-status-to-logs-as-interim-solution

- service-api/module/Application/src/Yoti/SessionConfig.php
- service-api/module/Application/src/Yoti/YotiService.php
- service-api/module/Application/test/ApplicationTest/Yoti/SessionConfigTest.php
> ID-269-Adjust-sessionConfig-to-accept-passports-ID-we-want-to-test

- .github/workflows/test.yml
- Makefile
Load cached images rather than rebuilding them
#patch
> Speed up Cypress tests

- docker/sirius/openapi.yml
> ID-320-Fix-Sirius-mock-issue-with-prefix-renaming

- service-api/module/Application/src/Controller/IdentityController.php
- service-api/module/Application/src/Fixtures/DataQueryHandler.php
- service-api/module/Application/test/ApplicationTest/Fixtures/DataQueryHandlerTest.php
Removing queries/indexes that are no longer needed and adding more test
Fixes ###-####
> ID-237-Cleanup-Add-missing-tests-for-DataQueryHandler

- Makefile
- service-front/module/Application/view/application/pages/cp/choose_country.twig
- service-front/module/Application/view/application/pages/post_office/choose_country.twig
- service-front/web/main.js
- service-front/web/main.scss
Enhance the existing selects to add autocomplete functionality, allowing typeahead search.
For ID-240 #minor
> Set up accessible autocomplete

- service-api/composer.json
- service-api/composer.lock
- service-api/config/modules.config.php
- service-api/module/Application/config/module.config.php
Add the soap dependency required for interacting with the KBV service, and laminas-di to reduce the amount of factory code required
* [] I have updated documentation where relevant
* [] I have added tests to prove my work
* [] I have run an accessibility tool against the changes and applied fixes
* [] The team have tested these changes
> ID-257 Add soap and laminas-di dependencies

- docker/sirius/openapi.yml
- e2e-tests/cypress/e2e/donor/counter-service.cy.ts
- service-api/docker/scripts/create-cert.php
- service-api/module/Application/src/Yoti/YotiService.php
- service-api/module/Application/src/Yoti/YotiServiceInterface.php
- service-front/module/Application/config/module.config.php
- service-front/module/Application/src/Controller/PostOfficeFlowController.php
- service-front/module/Application/view/application/pages/cp/how_will_the_cp_confirm.twig
- service-front/module/Application/view/application/pages/cp/post_office_documents.twig
- service-front/module/Application/view/application/pages/how_will_the_donor_confirm.twig
- service-front/module/Application/view/application/pages/post_office/confirm_post_office.twig
- service-front/module/Application/view/application/pages/post_office/find_post_office_branch.twig
- service-front/module/Application/view/application/pages/post_office/post_office_documents.twig
- service-front/module/Application/view/application/pages/post_office/post_office_route_not_available.twig
- service-front/module/Application/view/application/pages/post_office/what_happens_next.twig
- service-front/module/Application/view/application/pages/proving_identity.twig
> Capitalise Post Office properly

- docker-compose.override.yml
- e2e-tests/cypress/e2e/certificate_provider/certificate-provider-journey.cy.ts
Add Cypress to for CP happy path to ensure future changes to not break this functionality
Add test that mimic the user interacting with the service
> Add Cypress for CP happy path

- service-front/module/Application/src/Controller/PostOfficeFlowController.php
- service-front/module/Application/view/application/pages/post_office/find_post_office_branch.twig
> ID-337 removed no post office option#patch

- service-front/module/Application/config/module.config.php
- service-front/module/Application/src/Controller/DonorFlowController.php
- service-front/module/Application/src/Controller/Factory/DonorFlowControllerFactory.php
- service-front/module/Application/src/Controller/Factory/PostOfficeFlowControllerFactory.php
- service-front/module/Application/src/Controller/PostOfficeFlowController.php
- service-front/module/Application/view/application/pages/cp/cp_details_match_check.twig
- service-front/module/Application/view/application/pages/donor_details_match_check.twig
- service-front/module/Application/view/application/pages/post_office/donor_details_match_check.twig
> ID-334-Edit-the-donor-details-on-Sirius-page-should-take-user-to-Sirius

- docker/yoti/data/media_uk_passport.json
- docker/yoti/mediaRetrieval.groovy
- docker/yoti/yoti-config.yaml
- service-api/module/Application/src/Yoti/SessionStatusService.php
- service-api/module/Application/src/Yoti/YotiService.php
- service-api/module/Application/src/Yoti/YotiServiceInterface.php
- service-api/module/Application/test/ApplicationTest/Services/SessionStatusServiceTest.php
> ID-326-Check-expiry-date-of-passport-after-session-complete

- service-front/module/Application/config/module.config.php
- service-front/module/Application/src/Forms/PassportDate.php
- service-front/module/Application/src/Forms/PassportDateCp.php
- service-front/module/Application/src/Validators/PassportDateValidator.php
- service-front/module/Application/src/Validators/PassportInDateValidator.php
- service-front/module/Application/test/Helpers/FormProcessorHelperTest.php
- service-front/module/Application/test/Validators/PassportDateValidatorTest.php
- service-front/module/Application/view/application/pages/passport_number.twig
- service-front/module/Application/view/application/pages/passport_number_fail.twig
Fixes ID-335 - fix to 18 month expiry
> Switch to 18 months doe passport UI text and validators

- service-front/module/Application/view/application/pages/cp/cp_id_check.twig
update wording and formatting on cp/name-match-check page.
Fixes [ID-242](https://opgtransform.atlassian.net/browse/ID-242)
[ID-242]: https://opgtransform.atlassian.net/browse/ID-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update cp/name-match-check content

- docs/architecture/decisions/0005-store-external-service-availability-in-parameter-store.md
> Add ADR about tracking external integration availability

- service-front/module/Application/config/module.config.php
- service-front/module/Application/view/application/pages/how_will_the_donor_confirm.twig
reapply changes originally in #254 which were accidentally overwritten in #265 
Fixes ###-####
> re-apply content / format from ID-364 and ID-336

- docker/sirius/openapi.yml
- service-front/module/Application/config/module.config.php
- service-front/module/Application/src/Controller/DonorFlowController.php
- service-front/module/Application/src/Controller/PostOfficeFlowController.php
- service-front/module/Application/src/Enums/SiriusDocument.php
- service-front/module/Application/src/Services/SiriusApiService.php
- service-front/module/Application/test/Controller/DonorFlowControllerTest.php
- service-front/module/Application/test/Services/SiriusApiServicePactTest.php
- service-front/module/Application/view/application/pages/vouching_what_happens_next.twig
- service-front/module/Application/view/application/pages/what_is_vouching.twig
Adds the "what is vouching" and "what happens next" pages to the Donor journey.
Fixes: [ID-305](https://opgtransform.atlassian.net/browse/ID-305),  [ID-306](https://opgtransform.atlassian.net/browse/ID-306) #minor
[ID-305]: https://opgtransform.atlassian.net/browse/ID-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ID-306]: https://opgtransform.atlassian.net/browse/ID-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> what is vouching page

- docker-compose.yml
- docker/experian-crosscore/openapi.yml
- service-api/module/Application/src/Controller/IdentityController.php
- service-api/module/Application/src/Experian/Crosscore/FraudApi/DTO/ResponseDTO.php
- service-api/module/Application/src/Experian/Crosscore/FraudApi/FraudApiService.php
- service-api/module/Application/src/Model/Entity/CaseData.php
- service-api/module/Application/src/Model/Entity/FraudScore.php
- service-api/module/Application/test/ApplicationTest/Services/Experian/FraudApi/DTO/ExperianCrosscoreFraudResponseDTOTest.php
- service-api/module/Application/test/ApplicationTest/Services/Experian/FraudApi/ExperianCrosscoreFraudApiServiceTest.php
- service-api/module/Application/test/Controller/IdentityControllerTest.php
- service-front/module/Application/config/module.config.php
- service-front/module/Application/src/Contracts/OpgApiServiceInterface.php
- service-front/module/Application/src/Controller/CPFlowController.php
- service-front/module/Application/src/Controller/DonorFlowController.php
- service-front/module/Application/src/Helpers/FormProcessorHelper.php
- service-front/module/Application/src/Services/OpgApiService.php
- service-front/module/Application/test/Helpers/FormProcessorHelperTest.php
- service-front/module/Application/view/application/pages/fraud_failure.twig
> Feature/id 370 add =experian fraud check#major

- service-front/module/Application/view/application/pages/vouching_what_happens_next.twig
Fixes [ID-306](https://opgtransform.atlassian.net/browse/ID-306)
#patch
[ID-306]: https://opgtransform.atlassian.net/browse/ID-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix typo in what happens next page

- service-api/module/Application/src/Model/Entity/CaseData.php
- service-front/module/Application/src/Controller/CPFlowController.php
- service-front/module/Application/src/Controller/DonorFlowController.php
- service-front/module/Application/src/Controller/PostOfficeFlowController.php
- service-front/module/Application/src/Helpers/DateProcessorHelper.php
- service-front/module/Application/test/Controller/CPFlowControllerTest.php
- service-front/module/Application/test/Controller/DonorFlowControllerTest.php
- service-front/module/Application/test/Controller/KbvControllerTest.php
- service-front/module/Application/test/Controller/PostOfficeDonorFlowControllerTest.php
- service-front/module/Application/test/Services/OpgApiServiceTest.php
- service-front/module/Application/view/application/pages/donor_details_match_check.twig
- service-front/module/Application/view/application/pages/driving_licence_number.twig
- service-front/module/Application/view/application/pages/national_insurance_number.twig
- service-front/module/Application/view/application/pages/national_insurance_number_fail.twig
- service-front/module/Application/view/application/pages/passport_number.twig
- service-front/module/Application/view/application/pages/passport_number_fail.twig
- service-front/module/Application/view/application/pages/post_office/donor_details_match_check.twig
DOB shows in the donor journey UI
Fixes [ID-367](https://opgtransform.atlassian.net/browse/ID-367) #patch
I initially implemented this by replicating the existing approach, adding `$view->setVariable('dob_full', date_format(date_create($detailsData['dob']), "d F Y"));` to the methods where it was missing. This gave me a sonar-cloud failure for duplicated code, so I have created a Helper function to format the dates but i'm not sure if its really needed and we could just ignore the sonar-cloud warning.
Another option i did consider was adding a method to `CaseData` itself to return the `dob` formatted.
[ID-367]: https://opgtransform.atlassian.net/browse/ID-367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
> show DOB in donor id flow

- service-front/composer.lock
To get past a security vulnerability
#patch
`composer update symfony/process`
[Notified via a Dependabot PR](https://github.com/ministryofjustice/opg-paper-identity/pull/287), but Dependabot doesn't have permission to access our secrets so can't build
> Bump `symfony/process`

- service-front/composer.lock
To get past a security vulnerability
#patch
`composer update twig/twig`
[Notified via a Dependabot PR](https://github.com/ministryofjustice/opg-paper-identity/pull/290), but Dependabot doesn't have permission to access our secrets so can't build
> Bump `twig/twig`

- service-api/module/Application/src/Experian/Crosscore/FraudApi/DTO/ResponseDTO.php
- service-api/module/Application/src/Model/Entity/FraudScore.php
- service-api/module/Application/test/ApplicationTest/Services/Experian/FraudApi/DTO/ExperianCrosscoreFraudResponseDTOTest.php
- service-front/module/Application/test/Helpers/FormProcessorHelperTest.php
They're not used for anything elsewhere in the code.
#patch
> Remove decisionText and responseHeader from ResponseDTO

- docker-compose.yml
- docker/yoti/Dockerfile
- service-api/module/Application/src/Controller/IdentityController.php
- service-api/module/Application/src/Controller/KbvController.php
- service-api/module/Application/src/DrivingLicense/Validator.php
- service-api/module/Application/src/DrivingLicense/ValidatorFactory.php
- service-api/module/Application/src/Nino/Validator.php
- service-api/module/Application/src/Nino/ValidatorFactory.php
- service-api/module/Application/src/Passport/Validator.php
- service-api/module/Application/src/Passport/ValidatorFactory.php
- service-api/module/Application/src/Validators/LpaUidValidator.php
- service-api/module/Application/test/Controller/IdentityControllerTest.php
- service-api/module/Application/test/Controller/KbvControllerTest.php
- service-api/module/Application/test/Controller/YotiControllerTest.php
- service-api/module/Telemetry/Instrumentation/Aws.php
- service-front/module/Application/src/Helpers/AddressProcessorHelper.php
- service-front/module/Application/src/Services/OpgApiService.php
- service-front/module/Application/src/Validators/DLNDateValidator.php
- service-front/module/Application/src/Validators/LpaUidValidator.php
- service-front/module/Application/src/Validators/NinoValidator.php
- service-front/module/Application/src/Validators/PassportInDateValidator.php
- service-front/module/Application/test/Controller/CPFlowControllerTest.php
- service-front/module/Application/test/Services/OpgApiServiceTest.php
- service-front/module/Application/view/application/pages/driving_licence_number.twig
A bunch of low-hanging things identified by SonarCloud.
#patch
> SonarCloud fixes

- e2e-tests/cypress/e2e/donor/donor-journey.cy.ts
- service-front/module/Application/view/application/pages/how_will_the_donor_confirm.twig
Changes to the how will you confirm identity page for donor. To implement Figma: https://www.figma.com/design/pEYIyMBoWCGAvTclJFMOsq/Paper-ID-ideas?node-id=7979-43641&node-type=frame&t=GBRaEfV1izMR9N49-0
Markup changes
> ID-396 Content changes for donor confirm identity screen

- service-front/module/Application/src/Controller/DonorFlowController.php
It's printing onto the web page
#patch
> Remove echo statement

- service-front/module/Application/config/module.config.php
- service-front/module/Application/src/Contracts/OpgApiServiceInterface.php
- service-front/module/Application/src/Controller/VouchingFlowController.php
- service-front/module/Application/src/Enums/LpaActorTypes.php
- service-front/module/Application/src/Forms/VoucherName.php
- service-front/module/Application/src/Helpers/VoucherMatchLpaActorHelper.php
- service-front/module/Application/test/Controller/VouchingFlowControllerTest.php
- service-front/module/Application/test/Helpers/VoucherMatchLpaActorHelperTest.php
- service-front/module/Application/view/application/pages/vouching/what_is_the_voucher_name.twig
creates the "What is the name on their ID document?" page for the vouching journey.
Fixes [ID-267](https://opgtransform.atlassian.net/browse/ID-267)
Created a new helper class with a `checkNameMatch` method to return the actor-types which match a give first and last name. We can extend this class with additional methods for DOB and address checks later in the journey.
[ID-267]: https://opgtransform.atlassian.net/browse/ID-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> voucher name page

- docker/experian-iiq/iiq-response.js
So it's obvious which one you should select to get a particular outcome
Fixes ID-429 #patch
The answers are passed through as-is (rather than, say, by ID), so we can add a symbol to each of the correct ones.
* N/A
* N/A
* N/A
* N/A
> Mark correct answers in KBV mock

- service-front/module/Application/src/Controller/VouchingFlowController.php
fixes broken link in integration
"Donor will ID another way" button on confirm-vouching page.
> fix broken link on the donor will id another way button

- service-api/module/Application/src/Experian/Crosscore/FraudApi/FraudApiService.php
- service-api/module/Application/src/Factories/ExperianCrosscoreFraudApiServiceFactory.php
- service-api/module/Application/test/ApplicationTest/Services/Experian/FraudApi/ExperianCrosscoreFraudApiServiceTest.php
> Bugfix/id 427 experian logging#patch

- service-api/module/Application/config/module.config.php
- service-api/module/Application/src/Controller/IdentityController.php
- service-front/module/Application/config/module.config.php
- service-front/module/Application/src/Contracts/OpgApiServiceInterface.php
- service-front/module/Application/src/Controller/CPFlowController.php
- service-front/module/Application/src/Controller/VouchingFlowController.php
- service-front/module/Application/src/Forms/VoucherBirthDate.php
- service-front/module/Application/src/Helpers/FormProcessorHelper.php
- service-front/module/Application/src/Helpers/VoucherMatchLpaActorHelper.php
- service-front/module/Application/src/Services/OpgApiService.php
- service-front/module/Application/src/Services/SiriusApiService.php
- service-front/module/Application/test/Controller/IndexControllerTest.php
- service-front/module/Application/test/Controller/VouchingFlowControllerTest.php
- service-front/module/Application/test/Helpers/FormProcessorHelperTest.php
- service-front/module/Application/test/Helpers/VoucherMatchLpaActorHelperTest.php
- service-front/module/Application/view/application/pages/vouching/what_is_the_voucher_dob.twig
- service-front/module/Application/view/application/pages/vouching/what_is_the_voucher_name.twig
creates the voucher date-of-birth page
Fixes [ID-377](https://opgtransform.atlassian.net/browse/ID-377)
#minor
- update the voucher-name page to actually save the name to `CaseData`
- update the `VoucherMatchLpaActorHelper` class to enable filtering on matching dobs too
[ID-377]: https://opgtransform.atlassian.net/browse/ID-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ID-377 voucher date-of-birth page

- service-front/module/Application/view/application/pages/how_will_the_donor_confirm.twig
> Feature/id 431 donor content forced po#minor

- e2e-tests/cypress/e2e/certificate_provider/certificate-provider-journey.cy.ts
- service-front/module/Application/src/Controller/VouchingFlowController.php
- service-front/module/Application/src/Forms/VoucherBirthDate.php
- service-front/module/Application/src/Forms/VoucherName.php
- service-front/module/Application/src/Validators/BirthDateValidator.php
- service-front/module/Application/test/Controller/VouchingFlowControllerTest.php
- service-front/module/Application/view/application/pages/vouching/what_is_the_voucher_dob.twig
- service-front/module/Application/view/application/pages/vouching/what_is_the_voucher_name.twig
expands and fixes some validation/error messages on the voucher name and dob pages
Fixes [ID-377](https://opgtransform.atlassian.net/browse/ID-377)
[ID-377]: https://opgtransform.atlassian.net/browse/ID-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature/id 377/voucher dob error messages

- service-api/module/Application/src/Model/Entity/ClaimedIdentity.php
- service-api/module/Application/test/ApplicationTest/Model/Entity/CaseDataTest.php
- service-api/module/Application/test/Controller/IdentityControllerTest.php
first and last name are not available at the start of the vouching journey so we cannot require them in claimedIdentity
> fix claimedIdentity object in vouching journey

- service-front/module/Application/view/application/pages/cp/add_lpa.twig
> ID-416 fixing add LPA page#patch

- service-front/module/Application/view/application/pages/driving_licence_number_success.twig
- service-front/module/Application/view/application/pages/national_insurance_number_success.twig
- service-front/module/Application/view/application/pages/passport_number_success.twig
> ID-368-updating-page-content#minor

- e2e-tests/cypress/e2e/certificate_provider/certificate-provider-journey.cy.ts
> ID-438 adding cypress test for date#patch

- service-api/module/Application/src/Experian/Crosscore/AuthApi/AuthApiService.php
- service-api/module/Application/src/Factories/ExperianCrosscoreAuthApiServiceFactory.php
- service-api/module/Application/test/ApplicationTest/Services/Experian/AuthApi/ExperianCrosscoreAuthApiServiceTest.php
> Id 444 2 experian logging#patch

- docker/experian-crosscore/experian-crosscore-config.yaml
- service-api/module/Application/src/Controller/IdentityController.php
> Bugfix/id 445 cypress and date format#patch

- e2e-tests/cypress/e2e/donor/donor-journey.cy.ts
- service-front/module/Application/src/Helpers/FormProcessorHelper.php
- service-front/module/Application/test/Helpers/FormProcessorHelperTest.php
> ID-446 fixing tests & fraudscore rules#patch

- service-api/module/Application/src/Experian/Crosscore/FraudApi/FraudApiService.php
> ID-447 removing array#patch

- docker/sirius/data/addressResponse.json
- docker/sirius/data/countryListResponse.json
- docker/sirius/openapi.yml
- docker/sirius/sirius-config.yaml
- service-front/module/Application/src/Controller/CPFlowController.php
- service-front/module/Application/src/Controller/VouchingFlowController.php
- service-front/module/Application/src/Services/SiriusApiService.php
- service-front/module/Application/test/Controller/VouchingFlowControllerTest.php
- service-front/module/Application/view/application/pages/cp/enter_address_manual.twig
- service-front/module/Application/view/application/pages/vouching/enter_address_manual.twig
retrieve countrylist for address dropdown from sirius api
Fixes [ID-437](https://opgtransform.atlassian.net/browse/ID-437)
[ID-437]: https://opgtransform.atlassian.net/browse/ID-437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> retrieve countrylist for address dropdown from sirius api

- service-api/module/Telemetry/Instrumentation/Soap.php
> ID-452 capture config#patch

- service-api/module/Application/src/Model/Entity/CaseProgress.php
- service-api/module/Application/test/ApplicationTest/Model/Entity/CaseProgressTest.php
Add tests for CaseProgress validation
Ensure Form validation is behaving as expected
How to set up Form validation in unit tests
* [] I have added relevant logging with appropriate levels to my code
> ID-451 Add CaseProgress validation tests

- Makefile
To avoid hanging containers
#patch
> Remove cypress container after run

- service-api/module/Application/src/Experian/IIQ/AuthManager.php
Using https may have broken our IIQ auth
#patch
> Switch WSSE tags to http

- service-api/module/Application/src/Experian/IIQ/IIQService.php
- service-front/module/Application/src/Helpers/FormProcessorHelper.php
- service-front/module/Application/test/Helpers/FormProcessorHelperTest.php
To decipher why our test records are failing
#patch
> Add extra logging to error responses from Experian

- service-api/Dockerfile
> ID-457 - Pull Mozilla CA Cert Bundle directly from cURL hosted package #minor

- service-api/module/Application/src/Controller/IdentityController.php
- service-api/module/Application/src/Controller/KbvController.php
- service-api/module/Application/src/Experian/IIQ/ConfigBuilder.php
- service-api/module/Application/src/Helpers/ServiceAvailabilityHelper.php
- service-api/module/Application/src/Model/Entity/AbandonedFlow.php
- service-api/module/Application/src/Model/Entity/CaseData.php
- service-api/module/Application/src/Model/Entity/CaseProgress.php
- service-api/module/Application/src/Model/Entity/DocCheck.php
- service-api/module/Application/src/Model/Entity/Kbvs.php
- service-api/module/Application/test/ApplicationTest/Experian/IIQ/ConfigBuilderTest.php
- service-api/module/Application/test/ApplicationTest/Helplers/ServiceAvailabilityHelperTest.php
- service-api/module/Application/test/ApplicationTest/Model/Entity/AbandonedFlowTest.php
- service-api/module/Application/test/ApplicationTest/Model/Entity/CaseProgressTest.php
- service-api/module/Application/test/Controller/HealthcheckControllerTest.php
- service-api/module/Application/test/Controller/KbvControllerTest.php
- service-front/module/Application/src/Contracts/OpgApiServiceInterface.php
- service-front/module/Application/src/Controller/CPFlowController.php
- service-front/module/Application/src/Controller/DonorFlowController.php
- service-front/module/Application/src/Controller/IndexController.php
- service-front/module/Application/src/Controller/KbvController.php
- service-front/module/Application/src/Services/OpgApiService.php
- service-front/module/Application/test/Services/OpgApiServiceTest.php
Move relevant fields into case progress and refactor
> Feature/id 418 Update and refactor CaseProgress

- service-api/module/Application/src/Experian/Crosscore/FraudApi/DTO/ResponseDTO.php
- service-api/module/Application/test/ApplicationTest/Services/Experian/FraudApi/DTO/ExperianCrosscoreFraudResponseDTOTest.php
> ID-401 refactor fraudscore DTO & tests#minor

- service-front/module/Application/view/application/pages/cp/confirm_address_match.twig
Ensure the link works on integration as well as locally. Styling also added.
> ID-436: Fix for "Edit this address" button doesn't work and isn't styled properly

- docker/sirius/sirius-config.yaml
- e2e-tests/cypress/e2e/certificate_provider/certificate-provider-journey.cy.ts
- e2e-tests/cypress/e2e/certificate_provider/counter-service.cy.ts
- e2e-tests/cypress/e2e/donor/donor-journey.cy.ts
- service-front/module/Application/config/module.config.php
> ID-332 fixing LPA remove route and adding tests#minor

- service-front/module/Application/src/Controller/Factory/PostOfficeFlowControllerFactory.php
- service-front/module/Application/src/Controller/PostOfficeFlowController.php
- service-front/module/Application/view/application/pages/post_office/what_happens_next.twig
> Feature/id 333 return to sirius on po complete#minor

- e2e-tests/cypress/e2e/donor/donor-journey.cy.ts
- service-front/module/Application/view/application/pages/identity_check_failed.twig
minor content change to identity-check-failed page
fixes [ID-454](https://opgtransform.atlassian.net/browse/ID-454)
[ID-454]: https://opgtransform.atlassian.net/browse/ID-454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update message after failing kbvs

- service-front/module/Application/src/Controller/PostOfficeFlowController.php
> ID-406 display nation on non-uk id#minor

- service-front/module/Application/src/Forms/BirthDate.php
- service-front/module/Application/src/Forms/VoucherBirthDate.php
- service-front/module/Application/src/Helpers/FormProcessorHelper.php
- service-front/module/Application/src/Validators/BirthDateValidator.php
- service-front/module/Application/test/Controller/VouchingFlowControllerTest.php
- service-front/module/Application/test/Helpers/FormProcessorHelperTest.php
Fixes [ID-477](https://opgtransform.atlassian.net/browse/ID-477) bug which means dates entered with single digits for day or month are not saved.
[ID-477]: https://opgtransform.atlassian.net/browse/ID-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ID-477/zero-pad single digit days and months in dob form/#patch

- e2e-tests/cypress/e2e/certificate_provider/certificate-provider-journey.cy.ts
- e2e-tests/cypress/e2e/donor/donor-journey.cy.ts
- service-front/module/Application/view/application/pages/cp/cp_id_check.twig
- service-front/module/Application/view/application/pages/donor_details_match_check.twig
> ID-472 changing link and adding test#patch

- service-front/module/Application/view/application/pages/donor_details_match_check.twig
- service-front/module/Application/view/application/pages/donor_lpa_check.twig
- service-front/module/Application/view/application/pages/driving_licence_number.twig
- service-front/module/Application/view/application/pages/national_insurance_number.twig
- service-front/module/Application/view/application/pages/passport_number.twig
- service-front/module/Application/view/application/pages/post_office/confirm_post_office.twig
- service-front/module/Application/view/application/pages/post_office/find_post_office_branch.twig
- service-front/module/Application/view/application/pages/post_office/post_office_documents.twig
> ID-304 adding spacing to buttons#minor

- e2e-tests/cypress/e2e/certificate_provider/counter-service.cy.ts
- service-front/module/Application/src/Controller/PostOfficeFlowController.php
- service-front/module/Application/view/application/pages/post_office/post_office_documents.twig
> Bugfix/id 470 post office doc page validation#patch

- e2e-tests/cypress/e2e/donor/donor-journey.cy.ts
- service-front/module/Application/view/application/pages/donor_lpa_check.twig
> Feature/id 473 update lpa check page#patch

- service-front/module/Application/test/Controller/DocumentCheckControllerTest.php
- service-front/module/Application/test/Controller/HowConfirmControllerTest.php
- service-front/module/Application/test/Controller/VouchingFlowControllerTest.php
- service-front/module/Application/test/Validators/NinoValidatorTest.php
> Bugfix/id 495 unit testing deprecations#minor

- .docker.ignore
- service-api/Dockerfile
- service-api/config/development.config.php
- service-front/Dockerfile
> ID-496 - Remove Dev PHP Config from Production Images #minor

- service-api/docker-compose.env
- service-api/module/Application/src/Yoti/SessionConfig.php
- service-api/module/Application/test/ApplicationTest/Yoti/SessionConfigTest.php
Updates config to align with agreed values
Fixes [ID-180](https://opgtransform.atlassian.net/browse/ID-180)
[ID-180]: https://opgtransform.atlassian.net/browse/ID-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ID-180 update yoti session-config

- docker/sirius/data/certificateProvider.json
- docker/sirius/data/cpInProgress.json
- service-front/module/Application/src/Helpers/LpaFormHelper.php
- service-front/module/Application/src/Views/TwigExtension.php
- service-front/module/Application/test/Helpers/AddDonorFormHelperTest.php
- service-front/module/Application/test/Helpers/LpaFormHelperTest.php
- service-front/module/Application/view/application/pages/cp/add_lpa.twig
It is `in-progress` not `In progress`
For ID-481 #patch
Update code, tests and mocks. Add a `format_status` filter to translate statuses properly.
* N/A
* N/A
* N/A
* N/A
> Fix value of "In progress" status

- service-front/module/Application/view/application/pages/identity_check_passed.twig
updates to the donor "Identity check passed" page.
Fixes [ID-509](https://opgtransform.atlassian.net/browse/ID-509)
[ID-509]: https://opgtransform.atlassian.net/browse/ID-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ID-509 change structure of donor identity-check-passed page #patch

- .github/workflows/test.yml
- .github/workflows/workflow-main.yml
- service-api/module/Application/test/ApplicationTest/Yoti/Http/RequestSignerTest.php
- service-api/module/Application/test/ModuleTest.php
- service-api/phpunit.xml
- service-front/module/Application/test/ModuleTest.php
- service-front/phpunit.xml
adds code-coverage so we can see areas where our testing could be improved - we are not setting a required threshold/failing a pipeline based on coverage at this point.
Fixes ###-####
> add code-coverage to unit-tests

- service-front/module/Application/view/application/pages/confirm_dob.twig
update dob pages to match design
Fixes [ID-526](https://opgtransform.atlassian.net/browse/ID-526)
[ID-526]: https://opgtransform.atlassian.net/browse/ID-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ID-526 update dob pages to match design #patch

- e2e-tests/cypress/e2e/donor/donor-journey-locks.cy.ts
- service-front/module/Application/view/application/pages/how_will_you_confirm.twig
> ID-510 removed text on error #patch

- service-front/module/Application/src/Controller/KbvController.php
- service-front/module/Application/view/application/pages/document_success.twig
- service-front/module/Application/view/application/pages/identity_check_questions.twig
- service-front/module/Application/view/application/pages/national_insurance_number_fail.twig
- service-front/module/Application/view/application/pages/passport_number_fail.twig
> Feature/id 517 move explanation message to kbv screen#minor

- e2e-tests/cypress/e2e/certificate_provider/counter-service.cy.ts
- e2e-tests/cypress/e2e/donor/donor-journey.cy.ts
- e2e-tests/cypress/e2e/voucher/voucher-journey.cy.ts
- service-front/module/Application/view/application/pages/post_office/what_happens_next.twig
update text and formatting post-office what happens next
Fixes [ID-514](https://opgtransform.atlassian.net/browse/ID-514)
[ID-514]: https://opgtransform.atlassian.net/browse/ID-514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ID-514 update text and formatting post-office what happens next #patch

- e2e-tests/cypress/e2e/donor/donor-journey-locks.cy.ts
- service-api/module/Application/config/module.config.php
- service-api/module/Application/src/Helpers/ServiceAvailabilityHelper.php
- service-api/module/Application/src/Model/Entity/CaseData.php
- service-api/module/Application/test/ApplicationTest/Helpers/ServiceAvailabilityHelperTest.php
- service-front/module/Application/src/Contracts/OpgApiServiceInterface.php
- service-front/module/Application/src/Controller/CPFlowController.php
- service-front/module/Application/src/Controller/DonorFlowController.php
- service-front/module/Application/src/Controller/VouchingFlowController.php
- service-front/module/Application/src/Services/OpgApiService.php
- service-front/module/Application/test/Services/OpgApiServiceTest.php
> ID-528 refactoring service logic#minor

- .gitignore
- CODEOWNERS
- Makefile
- docker-compose.yml
- service-api/Dockerfile
- service-front/Dockerfile
Add local trivy image scanning, patch libxml2 vulnerability
> SP-2655 - Patch Vuln, add local scan targets, update Code Owners #minor

- service-front/module/Application/view/application/pages/how_will_you_confirm.twig
minor content change
Fixes [id-358](https://opgtransform.atlassian.net/browse/ID-538)
> id-358 driving-license address must match PO-letter text #patch

- e2e-tests/cypress/e2e/donor/donor-journey-locks.cy.ts
- service-api/module/Application/src/DWP/DwpApi/DwpApiService.php
- service-api/module/Application/src/Experian/IIQ/KBVService.php
- service-api/module/Application/src/Helpers/ServiceAvailabilityHelper.php
- service-api/module/Application/src/Model/Entity/IdentityIQ.php
- service-api/module/Application/test/ApplicationTest/Unit/Helpers/ServiceAvailabilityHelperTest.php
- service-front/module/Application/src/Controller/HowConfirmController.php
> ID-524 fixing thinfile error banner#minor

- e2e-tests/cypress/e2e/certificate_provider/certificate-provider-journey.cy.ts
- e2e-tests/cypress/e2e/certificate_provider/counter-service.cy.ts
- service-front/module/Application/test/Feature/Controller/CPFlowControllerTest.php
- service-front/module/Application/test/Feature/Controller/DonorFlowControllerTest.php
- service-front/module/Application/test/Feature/Controller/VouchingFlowControllerTest.php
- service-front/module/Application/view/application/pages/cp/confirm_address_match.twig
- service-front/module/Application/view/application/pages/cp/enter_address.twig
- service-front/module/Application/view/application/pages/cp/enter_address_manual.twig
- service-front/module/Application/view/application/pages/cp/select_address.twig
- service-front/module/Application/view/application/pages/donor_details_match_check.twig
- service-front/module/Application/view/application/pages/vouching/enter_postcode.twig
varys content on address pages dependent on id-route/method
Fixes [id-539](https://opgtransform.atlassian.net/browse/ID-539), [id-540](https://opgtransform.atlassian.net/browse/ID-540), [id-541](https://opgtransform.atlassian.net/browse/ID-541)
> id-539 id-540, id-541, post office address updates #minor

- docker/sirius/data/lpa404.json
- e2e-tests/cypress/e2e/donor/donor-journey-locks.cy.ts
- service-front/module/Application/src/Controller/IndexController.php
- service-front/module/Application/view/application/pages/cp/add_lpa.twig
> Bugfix/id 551 lpa 404 errror#minor

- service-front/module/Application/src/Contracts/OpgApiServiceInterface.php
- service-front/module/Application/src/Controller/CPFlowController.php
- service-front/module/Application/src/Controller/VouchingFlowController.php
- service-front/module/Application/src/Helpers/SiriusDataProcessorHelper.php
- service-front/module/Application/src/Services/OpgApiService.php
- service-front/module/Application/test/Feature/Controller/IndexControllerTest.php
> Bugfix/id 543 post office route data persistence#minor

- service-api/module/Application/src/Yoti/SessionConfig.php
- service-api/module/Application/test/ApplicationTest/Unit/Yoti/SessionConfigTest.php
> ID-547 adding expiry date exception#minor

- docker/sirius/sirius-config.yaml
- service-front/module/Application/src/Controller/IndexController.php
- service-front/module/Application/src/Controller/VouchingFlowController.php
- service-front/module/Application/src/Exceptions/LpaNotFoundException.php
- service-front/module/Application/src/Helpers/LpaFormHelper.php
- service-front/module/Application/src/Helpers/SiriusDataProcessorHelper.php
- service-front/module/Application/src/Services/SiriusApiService.php
- service-front/module/Application/test/Feature/Controller/IndexControllerTest.php
- service-front/module/Application/test/Feature/Controller/VouchingFlowControllerTest.php
- service-front/module/Application/test/Unit/Helpers/LpaFormHelperTest.php
- service-front/module/Application/test/Unit/Helpers/SiriusDataProcessorHelperTest.php
- service-front/module/Application/test/Unit/Services/SiriusApiServicePactTest.php
- service-front/module/Application/test/Unit/Services/SiriusApiServiceTest.php
handle 404 when requesting lpa better
Fixes [id-552](https://opgtransform.atlassian.net/browse/ID-552)
> id-552 handle 404 when requesting lpa better #minor

- service-front/module/Application/test/Feature/Controller/IndexControllerTest.php
> ID-555 fixing unit test#patch

- e2e-tests/cypress/e2e/certificate_provider/counter-service.cy.ts
- service-front/module/Application/src/PostOffice/DocumentType.php
- service-front/module/Application/src/PostOffice/DocumentTypeRepository.php
- service-front/module/Application/test/Feature/Controller/PostOfficeFlowControllerTest.php
- service-front/module/Application/view/application/pages/post_office/choose_country.twig
- service-front/module/Application/view/application/pages/post_office/choose_country_id.twig
> Feature/id 546 po flow intl dln#minor

- e2e-tests/cypress/e2e/donor/donor-journey-locks.cy.ts
- service-front/module/Application/src/Controller/KbvController.php
- service-front/module/Application/view/application/pages/identity_check_questions.twig
> Feature/id 554 kbv form error message#minor

- service-front/module/Application/view/application/pages/identity_check_questions.twig
fixes [ID-557](https://opgtransform.atlassian.net/browse/ID-557)
[ID-557]: https://opgtransform.atlassian.net/browse/ID-557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> id-557 fix formatting of kbv Q page and remove i-dont-know option

- README.md
update README.
Fixes [id-548](https://opgtransform.atlassian.net/browse/ID-548)
> more detailed README

- service-front/module/Application/view/application/pages/vouching/vouch_for_another_donor.twig
- service-front/module/Application/view/application/pages/vouching/what_is_the_voucher_name.twig
To fix a reflective XSS attack vulnerability
Fixes ID-575 #patch
> Use correct HTML attribute syntax

- service-api/module/Application/src/Controller/HealthcheckController.php
remove log-line which should have been removed before merging #502
> don't log all case details in route-availability #patch

- .github/workflows/workflow-main.yml
> SP-2996 - Switch to workflow_dispatch safe branch name generation #patch
