ministryofjustice/opg-paper-identity

docker-compose.yml
nginx/Dockerfile
nginx/default.conf.template
nginx/nginx.conf

Provides a nginx container so that PHP containers can run on FPM.
Config copied across from opg-sirius: a reusable nginx image with sensible security headers and logging built in, which is mapped to port 8000.
We should probably switch to the shared `311462405659.dkr.ecr.eu-west-1.amazonaws.com/sirius/nginx` image at some point.
* N/A
* N/A
* N/A
* N/A
* N/A

Add nginx container in front of frontend

---

Makefile
docker-compose.yml

In both cases, the `-web` container is needed because they need to be interactable over HTTP.
#patch

Refer to correct containers in startup/dependencies

---

docker-compose.yml
docker/sirius/openapi.yml
docs/architecture/decisions/0002-authentication-via-sirius.md
service-front/module/Application/config/module.config.php
service-front/module/Application/src/Auth/Listener.php
service-front/module/Application/src/Auth/ListenerFactory.php
service-front/module/Application/src/Factories/SiriusApiServiceFactory.php
service-front/module/Application/src/Services/SiriusApiService.php
service-front/module/Application/test/Auth/ListenerTest.php
service-front/module/Application/test/Services/SiriusApiServiceTest.php
service-front/phpunit.xml

Ensures user is authenticated with Sirius on each request.
Fixes ID-31 #minor
In local development, Sirius is replaced by a mock server that always returns 200.
* N/A
* N/A
* N/A

Add auth listener to front end

---

service-api/composer.json
service-api/composer.lock
service-api/module/Application/config/module.config.php
service-api/module/Application/src/Factories/LoggerFactory.php
service-api/module/Application/src/Module.php
service-api/module/Application/src/Services/Logging/OpgFormatter.php
service-api/psalm.xml
service-front/composer.json
service-front/composer.lock
service-front/module/Application/config/module.config.php
service-front/module/Application/src/Factories/LoggerFactory.php
service-front/module/Application/src/Module.php
service-front/module/Application/src/Services/Logging/OpgFormatter.php

If an exception is thrown in the controller it is absorbed and an error template is shown. Since we don't want to show the details of the error in the user-facing template, we need to explicitly log it during the EVENT_FINISH event.
Fixes ID-65 #minor
Sets up monolog with standard OPG logging output under the hood, but can just be fetched as LoggerInterface anywhere in code.
Duplication due to setting this up in both API and Frontend.
I didn't realise Laminas so aggressively swallowed errors.
* N/A
* N/A
* N/A
* N/A

Add logger, auto-log response exceptions

---

service-api/module/Application/config/module.config.php
service-api/module/Application/src/Module.php
service-api/module/Application/view/error/error.json
service-api/module/Application/view/layout/layout.phtml

Ensure we show proper JSON responses for API errors.
#minor
Laminas needs a template to fall back to, so we set up a basic JSON response as a final backstop.
Also adapt the logic in `Module.php` so that it catches unsuccessful responses and returns a proper JSON error with more information.

Add error handling response in API

---

.github/workflows/test.yml
Makefile

Each of our JUnit files uses a difference output format for the file name and line, none of which match the `EnricoMi/publish-unit-test-result-action` action we use to publish the results of tests.
Fixes ID-67 #patch
<details>
<summary>Demo</summary>
</details>
Add some quick `sed` scripts to manipulate the files and get them into the correct format.
See #50 for an example of annotations in action
I was surprised JUnit was more standardised for this!

Alter JUnit files to support annotations

---

docker-compose.yml
service-front/module/Application/src/Auth/Listener.php
service-front/module/Application/src/Auth/ListenerFactory.php
service-front/module/Application/test/Auth/ListenerTest.php
service-front/phpunit.xml

Tells Sirius where to redirect back to if the authentication attempt is successful.
This ensures unauthed users will be taken to the page they navigated to, rather than being taken to the Sirius home page.
Fixes ID-142 #minor
This is already built in to Sirius, so we just need to provide a `redirect` query parameter.
* N/A
* N/A
* N/A
* N/A

Include a backlink when redirecting to auth

---

service-api/module/Application/src/Controller/IdentityController.php
service-api/module/Application/test/Controller/IdentityControllerTest.php
service-front/module/Application/src/Exceptions/HttpException.php
service-front/module/Application/src/Module.php
service-front/module/Application/src/Services/OpgApiService.php
service-front/module/Application/src/Views/TwigExtension.php
service-front/module/Application/test/Services/OpgApiServiceTest.php
service-front/module/Application/view/error/index.twig

When a case isn't found, the user should get a clear 404 page rather than a half-filled 200 or a generic 500.
Fixes ID-143 #minor
This introduces the start of a framework around error handling:
Controllers and services can throw a `HttpException` to immediately jettison the request with a particular status code.
The Application module listener will intercept these to set the correct status code. The error template can also use this to show a custom error message.
When throwing OpgApiException, attach the Guzzle exception as previous, so that any code catching it can check the underlying error.
Then bring that all together so that `OpgApiService->getDetailsData()` can intercept Guzzle 404s and turn them into a `HttpException`.
Also fix an issue in API where it wasn't setting the correct …

Show a 404 error page if the case isn't found

---

docker/sirius/openapi.yml
service-front/module/Application/src/Controller/IndexController.php
service-front/module/Application/src/Services/SiriusApiService.php
service-front/module/Application/test/Controller/IndexControllerTest.php
service-front/module/Application/view/error/index.twig

If the donor details cannot be found in the LPA Store, fallback to the draft data found in Sirius.
As this is not possible for CPs, throw a 400 exception if a CP ID check is requested and their data isn't in the store.
Fixes ID-144 #minor
Updated the mock to occasionally return draft LPAs, but this can be forced by changing the mock to only ever return null from the store.
I introduced array shapes for response data from the Sirius API so that Psalm can more fully type-check all the array keys and values.
* N/A
* N/A
* N/A

Fallback to Sirius data

---

docker-compose.yml
service-front/module/Application/config/module.config.php
service-front/module/Application/src/Services/SiriusApiService.php
service-front/module/Application/src/Views/TwigExtension.php
service-front/module/Application/src/Views/TwigExtensionFactory.php
service-front/module/Application/view/error/index.twig

If `APP_DEBUG` is enabled, show additional error information on error pages.
This will make it easier to debug problems locally, but not change what's shown in remote environments.
The trace details could be nicer, but what we have is sufficient for now.
| Prod mode | Debug mode |
| --- | --- |
| ![Example error page with very little information](https://github.com/ministryofjustice/opg-paper-identity/assets/100852/d2db0d29-cc7a-4563-87a3-b84bae64a7aa) | ![Example error page with additional developer-focussed information](https://github.com/ministryofjustice/opg-paper-identity/assets/100852/64f58366-867b-4f8c-b059-6cbd654fe490) |
#minor
Introduced `APP_DEBUG` env var as that's commonly used in PHP frameworks (Symfony and Laravel). This is used to enable debug mode in Twig, and our custom …

Show enhanced error information in debug mode

---

service-api/module/Application/src/Controller/IdentityController.php
service-api/module/Application/src/Model/Entity/CaseData.php
service-api/module/Application/src/Module.php
service-api/module/Application/test/ApplicationTest/Model/Entity/CaseDataTest.php
service-api/module/Application/test/Controller/IdentityControllerTest.php

This is primarily to help debug something in the integration environment, but is also good practice.
Fixes ID-149 #minor
So rather than:
```json
{"status":400,"type":"HTTP400","title":"Bad Request"}
```
You get:
```json
{"type":"HTTP400","title":"Invalid data","error":{"dob":{"regexNotMatch":"Please enter a valid date of birth in the format YYYY-MM-DD"}}}
```
To enable that a couple of changes:
- If a body is already provided on an error response, don't overwrite it with the generic body. The generic body should just be used for uncaught errors
- Move `isValid` out of `CaseData`: the DTO should be responsible for defining its validation rules, but not for providing the validator. This _kind of_ removes a dependency in the DTO on laminas-form, as it's now just used for validation
I had to …

Improve error message when creating case

---

service-api/module/Application/src/Controller/IdentityController.php
service-api/module/Application/src/Fixtures/DataQueryHandler.php
service-api/module/Application/src/Model/Entity/CaseData.php
service-api/module/Application/src/Model/Entity/Problem.php
service-api/module/Application/src/Validators/IsType.php
service-api/module/Application/src/View/JsonModel.php
service-api/module/Application/test/ApplicationTest/Model/Entity/CaseDataTest.php
service-api/module/Application/test/Controller/IdentityControllerTest.php

The general goal here is that, rather than having to define the response shape in every controller action:
```php
$case = new CaseData(...);
return JsonModel([
'id' => $case->getId(),
// etc.
]);
```
You can just return the object:
```php
$case = new CaseData(...);
return JsonModel($case);
```
This has a few benefits:
- It ensures the data shape is consistent where multiple endpoints return the same shape (in particular, errors)
- It allows typed objects to be passed through methods more easily, rather than arrays that may or may not contain expected data (e.g. how DataQueryHandler->getCaseByUUID now returns CaseData)
- In turn, that forces us to define our data models better (I found that `kbvQuestions` and `documentComplete` were missing from `CaseData`)
- It will let us annotate the …

Return objects in API responses

---

service-api/module/Application/src/Controller/IdentityController.php
service-api/module/Application/src/Fixtures/DataImportHandler.php
service-api/module/Application/src/Fixtures/DataQueryHandler.php
service-api/module/Application/src/Model/Entity/CaseData.php
service-api/module/Application/src/Module.php
service-api/module/Application/test/ApplicationTest/Fixtures/DataImportHandlerTest.php
service-api/module/Application/test/Controller/IdentityControllerTest.php

We should use the `CaseData` DTO to pass data around, not arrays.
#patch
Perform the marshalling of the object inside the method rather than accepting an arbitrary array.
Also replace `CaseData->fromArray` with something generic.

Use CaseData in DataImportHandler->insertData

---

docker/sirius/openapi.yml
docs/pull_request_template.md

Can be used to find an address based on a postcode.
Fixes ID-164 #patch
Due to tooling limitations the mock returns a fixed response for the "description" property: it would normally be the concatenation of all the address lines, in order.

Add postcode lookup endpoint to Sirius mock

---

service-api/module/Application/src/Fixtures/DataImportHandler.php
service-api/module/Application/src/Model/Entity/CaseData.php
service-api/module/Application/src/Model/IdMethod.php
service-api/module/Application/src/Validators/Enum.php
service-api/module/Application/test/ApplicationTest/Fixtures/DataImportHandlerTest.php
service-api/module/Application/test/ApplicationTest/Model/Entity/CaseDataTest.php
service-api/module/Application/test/ApplicationTest/Validators/EnumTest.php

Make `DataImportHandler->updateCaseData` validate the property before saving.
Fixes ID-174 #patch
This highlighted that `idMethod` wasn't in CaseData, which I added. I also added a Enum to validate its values against and an Enum validator class.
* N/A
* N/A
* N/A
* N/A

Add field-level validation to CaseData update method

---

service-api/Dockerfile
service-front/Dockerfile

The version of OpenSSL (3.3.0) on the api and front images has a vulnerability.
Fixes ID-211 #patch
Use APK to upgrade the version on the image during build.

Upgrade version of OpenSSL used in images

---

service-front/Dockerfile

It was patching the wrong stage in a multi-stage build.
#patch

Move OpenSSL fix

---

Makefile
docker-compose.yml
scripts/localstack/init/localstack_init.sh

This avoids having keys on developers' machines, reducing the risk of them being committed to repos or otherwise shared.
#patch
Generate the key in the initialisation script inside localstack, rather than doing it on local machine and mounting it into the docker image.
To update a secret to another value, you can exec onto the box:
```sh
docker compose exec localstack awslocal secretsmanager put-secret-value --secret-id={SECRET_ID} --secret-string={SECRET_VALUE}
```

Move certificate generation into localstack

---

.github/workflows/test.yml
.github/workflows/workflow-main.yml
.gitignore
Makefile
docker-compose.yml
service-front/composer.json
service-front/composer.lock
service-front/module/Application/src/Services/SiriusApiService.php
service-front/module/Application/test/Services/SiriusApiServicePactTest.php
service-front/phpunit.xml

To form a contract between Paper ID and Sirius, allowing us to make changes in Sirius with the confidence that we won't break the Paper ID service.
Contract on Pact Broker: https://pact-broker.api.opg.service.justice.gov.uk/pacts/provider/sirius/consumer/paper-identity/latest
Fixes ID-173 #patch

Add pact tests for postcode lookup endpoint

---

service-front/yarn.lock

To pass a security issue on 3.0.2
Inspired by #156 but dependabot can't access secrets to do CI, and it removed all the integrity configuration.
#patch

Upgrade braces to 3.0.3

---

docker-compose.yml

v5.11.0 has an issue loading JSON files, so revert back to v5.8.2 #patch

Pin Prism to v5.8.2

---

docker/yoti/data/branches.json
service-api/module/Application/src/Controller/IdentityController.php
service-api/module/Application/src/Controller/YotiController.php
service-api/module/Application/src/Yoti/YotiService.php
service-api/module/Application/test/ApplicationTest/Services/YotiServiceTest.php
service-api/module/Application/test/Controller/YotiControllerTest.php
service-front/module/Application/src/Controller/DonorPostOfficeFlowController.php

This PR fixed a bug with post code attribute naming, which was incorrectly specified in Yoti docks and this build as reference with mocks and tests
It also fixes the different use of counterService->selectedPostOffice is being send from FE as an object rather than simply containing fad_code
Fixes ###-####

ID-291-donor-CP-bug-post-office-does-not

---

Makefile
scripts/localstack/init/localstack_init.sh
service-api/module/Application/test/ApplicationTest/Yoti/Http/RequestSignerTest.php

PHPCS, Psalm and PHPUnit tests should not require any dependencies to run, so should be run in `--no-deps` mode.
#patch
I rewrote `RequestSignerTest` to generate the SSL key in PHP rather than doing so via localstack. This saves about 15s when running the suite cold.
`front-unit-test` still needs to be run with dependencies to use Pact, but we'll be able to internalise that when Pact v10 is released.

Run test suites without dependencies

---

docker-compose.yml
docs/architecture/decisions/0004-managing-certificate-files.md
scripts/localstack/init/localstack_init.sh
service-api/Dockerfile
service-api/docker-compose.env
service-api/docker/php-entrypoint
service-api/docker/scripts/create-cert.php
service-api/module/Application/src/Aws/Secrets/AwsSecretsCache.php
service-api/module/Application/src/Module.php
service-api/module/Application/test/Aws/Secrets/AwsSecretsCacheTest.php
service-api/module/Application/test/Controller/IdentityControllerTest.php
service-api/module/Application/test/stubs/container.phpstub
service-api/psalm.xml

To be used when authenticating with the Experian IIQ API
Fixes ID-254 #minor
Create a folder `/opg-private` which is only read/writeable by the `www-data` user.
Add a new Docker entrypoint that creates a cert file in that folder based on secrets from Secrets Manager.
In local/CI builds, use the default PHP entrypoint instead since we won't be able to generate a valid cert file.
Plus a couple of fixes:
- Add placeholder cert secrets in localstack
- Remove extra slashes from secret IDs
- Add Psalm stub file for better typing on Psr\Container\ContainerInterface
* N/A
* N/A, though I've tested in a popup env
* N/A
* N/A, nothing to test

Create Experian IIQ cert file in bootstrap script

---

service-front/module/Application/src/Services/SiriusApiService.php
service-front/module/Application/test/Services/SiriusApiServiceTest.php

To pass authentication in write requests
Fixes ID-317 #patch
Extract header from cookie value
Sirius doesn't log XSRF errors very well, I'll improve things on the API side to make it clearer in the future.
* Will do in Sirius
* I've added it to [the documentation](https://opgtransform.atlassian.net/wiki/spaces/LS/pages/3645767693/How+authentication+works+in+Sirius)
* N/A
* N/A

Add XSRF header to Sirius requests

---

service-front/module/Application/src/Services/SiriusApiService.php
service-front/module/Application/test/Services/SiriusApiServicePactTest.php

The original ticket mis-named the field.
Update the tests to use the expected ID and a valid PDF.
For ID-110 #patch

`suffix` -> `pdfSuffix`

---

service-front/module/Application/src/Services/SiriusApiService.php

You currently can't start an ID check until the donor has submitted CP data, but they need to be able to perform ID checks before submission.
#minor
Only try to reformat the CP's address if it has been provided.

Remove dependency on LPA Store data

---

docker/yoti/openapi.yml
e2e-tests/cypress/e2e/donor/counter-service.cy.ts
service-front/module/Application/view/application/pages/cp/choose_country.twig
service-front/module/Application/view/application/pages/post_office/choose_country.twig

To establish a behavioural contract and ensure we don't break the journey in future changes.
Fixes ID-321 #patch
Required a change to the Yoti mock so that it always returns a required resource.
Added a missing label element on the "Choose country" page.
* N/A
* N/A
* N/A
* N/A

Add e2e donor counter service journey test

---

service-api/module/Application/src/Controller/YotiController.php

When Yoti sends a topic that we don't handle, log it to console.
This ensures we can track all notifications from Yoti for debugging, and will allow us to extend further in the future.
#patch

Log invalid topics

---

e2e-tests/cypress/e2e/donor/counter-service.cy.ts

Cypress tests needed to be updated to account for introduction of the autocomplete component.
#patch

Fix autocomplete Cypress tests

---

service-api/docker-compose.env
service-api/module/Application/config/module.config.php
service-api/module/Application/src/Controller/IdentityController.php
service-api/module/Application/src/Controller/YotiController.php
service-api/module/Application/src/Fixtures/DataWriteHandler.php
service-api/module/Application/src/Yoti/SessionStatusService.php
service-api/module/Application/test/ApplicationTest/Fixtures/DataImportHandlerTest.php
service-api/module/Application/test/ApplicationTest/Fixtures/DataWriteHandlerTest.php
service-api/module/Application/test/ApplicationTest/Services/SessionStatusServiceTest.php
service-api/module/Application/test/Controller/IdentityControllerTest.php
service-api/module/Application/test/Controller/YotiControllerTest.php

This PR refactors data handling areas, **_DataImportHandler_** was originally created to import data for initial project tasks, but to reflect actual use now been renamed to **_DataWriteHandler_**
It also makes use of dynamoDbs putItem() feature to also to update the entire $caseData at once rather than making several calls to update specific elements of it. 
Fixes ###-####

ID-328-Refactor-dynamo-dataHandling

---

docker/sirius/openapi.yml
service-api/config/autoload/aws.global.php
service-api/module/Application/config/module.config.php
service-api/module/Application/src/Aws/EventBridgeClientFactory.php
service-api/module/Application/src/Factories/EventSenderFactory.php
service-api/module/Application/src/Sirius/EventSender.php
service-api/module/Application/src/Yoti/SessionStatusService.php
service-api/module/Application/test/ApplicationTest/Services/SessionStatusServiceTest.php
service-api/module/Application/test/ApplicationTest/Sirius/EventSenderTest.php
service-front/module/Application/src/Controller/CPFlowController.php
service-front/module/Application/src/Controller/DonorFlowController.php
service-front/module/Application/src/Controller/IndexController.php
service-front/module/Application/src/Controller/PostOfficeFlowController.php
service-front/module/Application/src/Services/SiriusApiService.php
service-front/module/Application/test/Controller/IndexControllerTest.php

When the PO session is completed, send a success/failure event to Sirius so it can update records accordingly.
Fixes ID-183 #minor
Add EventBridge client and use putEvents. Created a EventSender class to wrap AWS logic.

Send Post Office results to EventBridge

---

service-front/module/Application/src/Controller/CPFlowController.php
service-front/module/Application/src/Controller/PostOfficeFlowController.php
service-front/module/Application/test/Controller/CPFlowControllerTest.php
service-front/module/Application/test/Controller/PostOfficeDonorFlowControllerTest.php
service-front/module/Application/view/application/pages/cp/how_will_the_cp_confirm.twig
service-front/module/Application/view/application/pages/how_will_the_donor_confirm.twig

Content fixes for ID-324
Fixes ID-324 #patch
- Correct spelling of "EEA"
- Don't include GBR in list of international countries
I've not used the DOM crawler assertions in laminas-test before, they're pretty straightforward to use.
* N/A
* N/A
* N/A
* N/A

Content fixes for ID-324

---

service-api/module/Application/config/module.config.php
service-api/module/Application/src/Experian/IIQ/IIQService.php
service-api/module/Application/src/Experian/IIQ/KBVService.php
service-api/module/Application/src/Experian/IIQ/Soap/IIQClient.php
service-api/module/Application/src/Experian/IIQ/Soap/IIQClientFactory.php
service-api/module/Application/test/ApplicationTest/Experian/IIQ/IIQServiceTest.php
service-api/module/Application/test/ApplicationTest/Experian/IIQ/KBVServiceTest.php

Having generated an auth token for IIQ, use it to send an SAA request to the service.
For ID-257 #minor
Similar architectural approach to adding WaspService. Updated KBVService to fetch questions rather than generating a token.
* N/A
* N/A

Use IIQ auth token to fetch questions

---

service-api/module/Application/config/module.config.php
service-api/module/Application/src/Experian/IIQ/AuthManager.php
service-api/module/Application/src/Experian/IIQ/AuthManagerFactory.php
service-api/module/Application/src/Experian/IIQ/IIQService.php
service-api/module/Application/src/Experian/IIQ/Soap/IIQClientFactory.php
service-api/module/Application/test/ApplicationTest/Experian/IIQ/AuthManagerTest.php
service-api/module/Application/test/ApplicationTest/Experian/IIQ/IIQServiceTest.php

Reduce how often we generate a new token from the IIQ auth API
Fixes ID-258 #patch
Rather than generating an auth token in the factory, which means it's generated every time the dependency is injected (even if it's not used), do it explicitly when making a call to the API.
Also, cache the token for 25 minutes to avoid generating new ones unnecessarily.
Not so much learning as a solemn reminder that factory chains can cause a lot of things to be constructed/generated that you don't really want.
* N/A
* N/A
* N/A
* N/A

Only generate IIQ auth only when needed

---

service-api/module/Application/config/module.config.php
service-api/module/Application/src/Controller/IdentityController.php
service-api/module/Application/src/Controller/KbvController.php
service-api/module/Application/test/Controller/IdentityControllerTest.php
service-api/module/Application/test/Controller/KbvControllerTest.php

Dependency injection means that the KBVService (and all its dependencies) is initialised for any controller that references it in the constructor.
By sharding the controllers and only depending what we need, we only initialise SoapClients when necessary and speed up every other page.
For ID-339 #patch

Split API KBV routes into separate controller

---

service-api/module/Application/src/Experian/IIQ/AuthManager.php
service-api/module/Application/src/Experian/IIQ/AuthManagerFactory.php
service-api/module/Application/src/Experian/IIQ/IIQService.php
service-api/module/Application/test/ApplicationTest/Experian/IIQ/IIQServiceTest.php

The IIQ token expires after several hours, or at midnight. Update the TTL of the token to keep it around for longer, and add a retry mechanism if the request fails.
For ID-257 #patch
The `withAuthentication` wrapper will try to make the call a maximum of twice: if the first call fails specifically with an authorization error, it will force-generate a new token and try again. Otherwise it will fail first time.
A re-learning of how to replace `withConsecutive` in PHPUnit.

Add retry for IIQ auth

---

service-front/module/Application/test/Services/SiriusApiServicePactTest.php

testAbandonCase needs a Digital LPA to exist and needs to use its UID in the request body
#patch

Setup state for abandon case test

---

service-api/module/Application/src/Experian/IIQ/KBVService.php
service-api/module/Application/src/KBV/KBVServiceInterface.php
service-api/module/Application/src/Mock/KBV/KBVService.php
service-api/module/Application/test/ApplicationTest/Experian/IIQ/KBVServiceTest.php
service-front/module/Application/src/Contracts/OpgApiServiceInterface.php
service-front/module/Application/src/Controller/KbvController.php
service-front/module/Application/test/Controller/KbvControllerTest.php
service-front/module/Application/test/Services/OpgApiServiceTest.php
service-front/module/Application/view/application/pages/identity_check_questions.twig

"experianId" => "externalId", since the supplier is an implementation detail.
And remove leftover "answer" properties which aren't used.
For ID-345 #patch

Tidy up question model

---

service-api/module/Application/src/Controller/KbvController.php
service-api/module/Application/src/Experian/IIQ/ConfigBuilder.php
service-api/module/Application/src/Experian/IIQ/IIQService.php
service-api/module/Application/src/Experian/IIQ/KBVService.php
service-api/module/Application/src/KBV/AnswersOutcome.php
service-api/module/Application/src/KBV/KBVServiceInterface.php
service-api/module/Application/src/Mock/KBV/KBVService.php
service-api/module/Application/test/ApplicationTest/Experian/IIQ/ConfigBuilderTest.php
service-api/module/Application/test/ApplicationTest/Experian/IIQ/IIQServiceTest.php
service-api/module/Application/test/ApplicationTest/Experian/IIQ/KBVServiceTest.php
service-api/module/Application/test/Controller/KbvControllerTest.php
service-front/module/Application/src/Contracts/OpgApiServiceInterface.php
service-front/module/Application/src/Controller/KbvController.php
service-front/module/Application/src/Services/OpgApiService.php
service-front/module/Application/test/Controller/KbvControllerTest.php
service-front/module/Application/test/Services/OpgApiServiceTest.php

Submit KBV answers to IIQ API to check if they are correct.
Fixes ID-260 #minor
When answers are submitted by the front-end, submit them via RTQ. Depending on the response, either return the KBV pass/fail result or add more questions to be answered.
In the front-end, either redirect to the pass/fail results screen or refresh the page if there are more questions to answer.
I changed the internal API response from a boolean to an object to handle the additional complexity of whether the KBV check is incomplete.
* N/A

Send KBV answers

---

docker/experian-iiq/iiq-response.js
e2e-tests/cypress/e2e/certificate_provider/certificate-provider-journey.cy.ts
e2e-tests/cypress/e2e/donor/donor-journey.cy.ts
e2e-tests/cypress/support/commands.ts
e2e-tests/cypress/support/index.d.ts

It now handles pass/fail and setting more questions, following the same logic as the real API. It continues to use the mock questions from ID-82.
Also adds KBV pages to the happy path end-to-end journeys and adds a KBV failure end-to-end journey.
Fixes ID-346 #patch
Used Imposter's "stores" functionality to save data between requests based on the URN.
I added a `selectKBVAnswer` Cypress method to easily allow selecting a correct or incorrect answer based on the mock data set.
* N/A
* N/A
* N/A
* N/A

Update IIQ mock

---

service-api/module/Application/src/Model/Entity/CaseData.php
service-api/module/Application/test/ApplicationTest/Yoti/SessionConfigTest.php
service-front/module/Application/src/Contracts/OpgApiServiceInterface.php
service-front/module/Application/src/Controller/CPFlowController.php
service-front/module/Application/src/Controller/PostOfficeFlowController.php
service-front/module/Application/src/Helpers/AddressProcessorHelper.php
service-front/module/Application/src/Helpers/FormProcessorHelper.php
service-front/module/Application/src/Services/OpgApiService.php
service-front/module/Application/test/Services/OpgApiServiceTest.php

To better document API and identify mistaken assumptions.
In a few places, replace `array` return types with `void` because we only use the array value to check the request was successful, but that's implicit from no exception being thrown.
#patch

Improve typing of OpgApiServiceInterface

---

service-api/module/Application/src/Controller/IdentityController.php
service-api/module/Application/src/Experian/IIQ/ConfigBuilder.php
service-api/module/Application/src/Experian/IIQ/KBVService.php
service-api/module/Application/src/KBV/KBVServiceInterface.php
service-api/module/Application/src/Mock/KBV/KBVService.php
service-api/module/Application/src/Model/Entity/CaseData.php
service-api/module/Application/src/Model/Entity/CaseProgress.php
service-api/module/Application/src/Model/Entity/CounterService.php
service-api/module/Application/src/Model/Entity/Entity.php
service-api/module/Application/src/Model/Entity/IIQControl.php
service-api/module/Application/src/Model/Entity/KBVQuestion.php
service-api/module/Application/test/ApplicationTest/Experian/IIQ/ConfigBuilderTest.php
service-api/module/Application/test/ApplicationTest/Experian/IIQ/KBVServiceTest.php
service-api/module/Application/test/ApplicationTest/Fixtures/DataWriteHandlerTest.php
service-api/module/Application/test/Controller/KbvControllerTest.php
service-front/module/Application/src/Contracts/OpgApiServiceInterface.php
service-front/module/Application/test/Controller/CPFlowControllerTest.php
service-front/module/Application/test/Controller/DonorFlowControllerTest.php
service-front/module/Application/test/Controller/PostOfficeDonorFlowControllerTest.php
service-front/module/Application/test/Helpers/LpaFormHelperTest.php

Rather than store things as arrays, or as JSON encoded strings, store them as well-defined objects.
Fixes ID-352 #patch
To play nice with DynamoDB, the subclasses need to be instances of Traversable, so I've introduced an `Entity` base class to handle that.
The introduce of a KBVQuestion entity means other classes can be more strictly typed, rather than relying on an array shape.
I also updated the type hints of CaseData to be more accurate, which led to the disposal of the now-unused field `selectedPostOfficeDeadline`.
- DynamoDB's `marshalValue` is quite helpful when you meet its requirements (i.e. using Traversable)
- `properties-of<self>` is a helpful Psalm annotation for methods like `fromArray` and `toArray`
* N/A
* N/A
* N/A
* N/A

Use objects for CaseData model

---

service-api/Dockerfile
service-api/composer.json
service-api/composer.lock
service-api/module/Application/src/Aws/DynamoDbClientFactory.php
service-api/module/Telemetry/Instrumentation/Aws.php
service-api/module/Telemetry/Instrumentation/Guzzle.php
service-api/module/Telemetry/Instrumentation/Laminas.php
service-api/module/Telemetry/Instrumentation/Soap.php
service-api/module/Telemetry/Propagation/PsrRequest.php
service-api/module/Telemetry/Tracer.php
service-api/public/index.php
service-front/Dockerfile
service-front/composer.json
service-front/composer.lock
service-front/module/Telemetry/Instrumentation/Guzzle.php
service-front/module/Telemetry/Instrumentation/Laminas.php
service-front/module/Telemetry/Propagation/PsrRequest.php
service-front/module/Telemetry/Tracer.php
service-front/public/index.php

Add basic telemetry for HTTP requests and AWS calls
<details>
<summary>Example traces</summary>
Trace map when generating a counter service letter ([link](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#xray:traces/1-dc7218e5-fe2f86da07b3edccf3750e82)):
Segment timeline for the same request (1400ms on four Yoti queries, 700ms generating the PDF file):
Segment timeline for a failing request to generate KBV questions ([link](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#xray:traces/1-fe7e2cff-b6148b23650958074c6865af)) (I need to add instrumentation for SoapClient)
</details>
For CTC-180 #patch
Followed [model from Sirius](https://opgtransform.atlassian.net/wiki/spaces/LS/pages/3995926540/Telemetry+in+Sirius) (and stole a lot of the …

Add telemetry to Paper ID services

---

Makefile

To prevent error messages running `front-unit-test` if you don't intend to publish (e.g. locally)
#patch

Only publish pacts if password provided

---

service-front/module/Application/src/Controller/CPFlowController.php
service-front/module/Application/src/Controller/DonorFlowController.php
service-front/module/Application/src/Controller/IndexController.php
service-front/module/Application/src/Controller/PostOfficeFlowController.php
service-front/module/Application/src/Controller/Trait/FormBuilder.php
service-front/module/Application/src/Forms/AbandonFlow.php
service-front/module/Application/src/Forms/AddressJson.php
service-front/module/Application/src/Forms/ConfirmAddress.php
service-front/module/Application/src/Forms/Country.php
service-front/module/Application/src/Forms/CountryDocument.php
service-front/module/Application/src/Forms/CpAltAddress.php
service-front/module/Application/src/Forms/DrivingLicenceNumber.php
service-front/module/Application/src/Forms/FormTemplate.php
service-front/module/Application/src/Forms/IdMethod.php
service-front/module/Application/src/Forms/LpaReferenceNumber.php
service-front/module/Application/src/Forms/NationalInsuranceNumber.php
service-front/module/Application/src/Forms/PassportDate.php
service-front/module/Application/src/Forms/PassportDateCp.php
service-front/module/Application/src/Forms/PassportDatePo.php
service-front/module/Application/src/Forms/PassportNumber.php
service-front/module/Application/src/Forms/PostOfficeAddress.php
service-front/module/Application/src/Forms/PostOfficeSearchLocation.php
service-front/module/Application/src/Forms/Postcode.php
service-front/module/Application/src/Helpers/FormProcessorHelper.php
service-front/module/Application/src/Helpers/LpaFormHelper.php
service-front/module/Application/src/Services/SiriusApiService.php
service-front/module/Application/test/Helpers/FormProcessorHelperTest.php
service-front/module/Application/test/Helpers/LpaFormHelperTest.php

Forms define the shape of the data model they represent in a top-level annotation.
This allows downstream code to call `$form->getData()` and know exactly what data it's getting.
As well as improving type-handling through the application, this prevents passing POST data directly to the API.
#patch

Use type templates on forms

---

service-api/module/Application/src/Experian/Crosscore/AuthApi/AuthApiService.php
service-api/module/Application/src/Factories/ExperianCrosscoreFraudApiServiceFactory.php
service-api/module/Application/test/ApplicationTest/Services/Experian/AuthApi/ExperianCrosscoreAuthApiServiceTest.php
service-api/module/Application/test/ApplicationTest/Services/Experian/FraudApi/ExperianCrosscoreFraudApiServiceTest.php

- Remove `AuthApiService->getCredentials()` to prevent secrets from leaking
- Use `Container->get()` rather than duplicating the AuthApiService build steps
- Type mocks correctly with MockObject for Psalm
#patch

Tidy up CrossCore classes

---

service-front/module/Application/view/application/pages/cp/how_will_the_cp_confirm.twig

Remove "other methods" from CP page "How will they confirm identity"
Fixes ###-####
Deleted the relevant code

ID-399 - CP page "How will they confirm identity" remove "other methods"

---

service-front/module/Application/view/layout/id_check_banner.twig

Exit ID link was not taking into account the base path: `/lpa/identity-check`
Fixes https://opgtransform.atlassian.net/browse/ID-398
Using twig filter `basepath` which grabs it from the environment variable `PREFIX`
Tested locally and on an isolated deployment at https://id-398.development.sirius.opg.service.justice.gov.uk/

ID-398 - Fix Paper ID "Exit ID" not working

---

service-api/module/Application/src/Controller/IdentityController.php
service-api/module/Application/src/Experian/IIQ/ConfigBuilder.php
service-api/module/Application/src/Experian/IIQ/IIQService.php
service-api/module/Application/src/Model/Entity/CaseData.php
service-api/module/Application/src/Model/Entity/VouchingFor.php
service-api/module/Application/src/Yoti/SessionConfig.php
service-front/module/Application/config/module.config.php
service-front/module/Application/src/Controller/IndexController.php
service-front/module/Application/src/Controller/VouchingFlowController.php
service-front/module/Application/src/Forms/ConfirmVouching.php
service-front/module/Application/src/Services/OpgApiService.php
service-front/module/Application/test/Controller/VouchingFlowControllerTest.php
service-front/module/Application/view/application/pages/vouching/confirm_vouching.twig
service-front/module/Application/view/layout/id_check_banner.twig

Create the start of the vouching route with the "confirm vouching" page
Fixes [ID-265](https://opgtransform.atlassian.net/browse/ID-265)
Setup a `VouchingFlowController` and allow for a new personType (voucher). When the process is started with `personType === voucher` then you are directed to the "confirm vouching" page.
Have added a `vouchingFor` field to `CaseData` which is populated with the name of the donor linked to the LPA. I also needed to make the fields associated with the donor in the other journeys (dob, name, address) non-required, defaulting to null/empty as this is info which will be provided by the voucher later in the vouching journey. This has had some knock on impacts on some validation checks and tests.
[ID-265]: …

vouching route - confirm vouching

---

docker/experian-crosscore-auth/openapi.yml
docker/experian-crosscore/openapi.yml
e2e-tests/cypress/e2e/donor/donor-journey.cy.ts
service-api/docker-compose.env
service-api/module/Application/src/Experian/Crosscore/AuthApi/DTO/RequestDTO.php
service-api/module/Application/src/Experian/Crosscore/FraudApi/FraudApiService.php
service-api/module/Application/test/ApplicationTest/Services/Experian/AuthApi/DTO/ExperianCrosscoreAuthRequestDTOTest.php

Send the correct fields to CrossCore auth so that we 
Fixes ID-425 #patch
Update the property names on RequestDTO to match spec. Update OpenAPI spec to require those fields.
This highlighted the importance of marking required fields in the OpenAPI spec: because they were optional, the mock server was happy to process the request and misrepresented how the live service would work.
* N/A
* N/A

Fix CrossCore auth request params

---

service-api/composer.json
service-api/composer.lock
service-front/composer.json
service-front/composer.lock

To ensure Renovate runs dependency checks against the correct version (rather than defaulting to latest, which doesn't work).
#patch

Specify PHP version

---

renovate.json

Otherwise, Renovate still tries to upgrade PHP when doing a Composer dependency update, which will always fail.
#patch

Don't upgrade PHP in packages

---

docker/experian-iiq/iiq-response.js
service-api/module/Application/src/Experian/IIQ/IIQService.php
service-api/module/Application/test/ApplicationTest/Experian/IIQ/IIQServiceTest.php
service-front/module/Application/src/Helpers/FormProcessorHelper.php
service-front/module/Application/test/Helpers/FormProcessorHelperTest.php

Previously, thin file errors caused generic failure message because `NextTransId` was always expected to be "RTQ". This now handles the two expected outcomes explicitly, and logs a more detailed error message if they're not met.
Also update the IIQ mock to return a representative response, and remove some debug logging added to FormProcessorHelper that isn't needed any more.
Fixes ID-458 #patch

Properly handle IIQ thin file errors

---

service-api/module/Application/config/module.config.php
service-api/module/Application/src/Controller/IdentityController.php
service-api/module/Application/test/Controller/IdentityControllerTest.php
service-api/module/Application/test/Controller/YotiControllerTest.php
service-front/module/Application/config/module.config.php
service-front/module/Application/src/Contracts/OpgApiServiceInterface.php
service-front/module/Application/src/Controller/Factory/IndexControllerFactory.php
service-front/module/Application/src/Controller/IndexController.php
service-front/module/Application/src/Exceptions/StartupException.php
service-front/module/Application/src/Services/OpgApiService.php
service-front/module/Application/src/Services/SiriusApiService.php
service-front/module/Application/test/Controller/IndexControllerTest.php
service-front/module/Application/test/Services/OpgApiServiceTest.php
service-front/module/Application/test/Services/SiriusApiServicePactTest.php
service-front/module/Application/view/application/pages/abandoned_flow.twig

Rather than using an API request, use events for consistency with other results.
Fixes ID-442 #minor
I added some more tests for the frontend and fixed the link of the "No" button.
* N/A
* N/A

Send event to Sirius when abandoning case

---

service-front/module/Application/src/Controller/VouchingFlowController.php
service-front/module/Application/src/Helpers/AddDonorFormHelper.php
service-front/module/Application/test/Controller/VouchingFlowControllerTest.php
service-front/module/Application/test/Helpers/AddDonorFormHelperTest.php
service-front/module/Application/view/application/pages/vouching/confirm_donors.twig

Make sure to fallback to `opg.poas.sirius` when `opg.poas.lpastore` is not available on the vouching route - specifically the confirm-donor and add-donor pages.

fallback to sirius when no lpastore, vouching add-donor pages

---

e2e-tests/cypress/e2e/certificate_provider/certificate-provider-journey.cy.ts
e2e-tests/cypress/e2e/donor/donor-journey.cy.ts
service-front/module/Application/view/application/pages/how_will_you_confirm.twig
service-front/module/Application/view/application/pages/passport_number.twig
service-front/module/Application/view/application/pages/post_office/post_office_documents.twig

To recreate - start an ID check, and on that page select the passport option and open the reveal and enter a date and click check. The page refreshes and the passport option is unchecked. 
This is frustrating because each user after they had checked would scroll down to the continue button and then get the error and then have to select the radio button again. 
Can this radio button stay as checked after the passport date has been checked please. 
Fixes https://opgtransform.atlassian.net/browse/ID-467
`<input class="govuk-radios__input" id="inDateFalse" name="inDate" type="radio"
value="no" {{ (form.get('inDate').value == 'no') ? 'checked' : '' }}>`

Prevent value being lost from Passport in date on form submission

---

docker/sirius/data/donor.json
docker/sirius/data/donorNoDecision.json
docker/sirius/data/donorNoDecisionKBV.json
docker/sirius/data/donorRefer.json
docker/sirius/data/donorStop.json
service-front/module/Application/src/Controller/IndexController.php
service-front/module/Application/src/Services/SiriusApiService.php

When starting the journey, when we fetch the data from Sirius: if there is already a valid ID check against the actor, do not allow them to start the process and show an error page explaining that the ID check is already complete.

Display error if identity check complete

---

service-front/module/Application/view/application/pages/how_will_you_confirm.twig
service-front/module/Application/view/application/pages/post_office/find_post_office_branch.twig
service-front/module/Application/view/application/pages/vouching/confirm_vouching.twig
service-front/module/Application/view/application/pages/vouching/vouch_for_another_donor.twig

They need to match the `id` of the input they relate to
Fixes ID-522 #patch
I searched templates for `for="` and checked they matched the inputs
* N/A
* N/A
* N/A
* N/A

Fix `for` attributes

---

service-api/module/Application/src/Validators/LpaUidValidator.php
service-api/module/Application/test/ApplicationTest/Validators/LpaUidValidatorTest.php
service-front/module/Application/src/Validators/LpaUidValidator.php
service-front/module/Application/test/Validators/LpaUidValidatorTest.php

Ensure LpaUidValidator requires strings to *be* UIDs not *contain* UIDs.
Fixes ID-521 #patch
Added `^` and `$` to regex pattern.
Renamed LpaValidatorTest to LpaUidValidatorTest
Removed `strtoupper` because we shouldn't manipulate input in validators. If we wantt o make things upper case, we need to do so in a filter.
* N/A
* N/A
* N/A

Add boundary assertions to LpaUidValidator

---

e2e-tests/cypress/e2e/certificate_provider/certificate-provider-journey.cy.ts
e2e-tests/cypress/e2e/donor/donor-journey.cy.ts
service-front/module/Application/view/application/pages/cp/cp_id_check.twig
service-front/module/Application/view/application/pages/donor_details_match_check.twig

Got on a call with @jrattle and found that the link wasn't quite right to update the donor and cert provider details on Sirius. This PR fixes that.

Fix link to update details on Sirius

---

service-api/Dockerfile
service-api/docker/php/memory_limit.ini
service-front/Dockerfile
service-front/docker/php/memory_limit.ini

GitHub Actions warned us that setting memory_limit to 4GB is higher than permissible. Also, that number is overridden in the container by PHP FPM config.
Fixes ID-534 #patch
Remove memory_limit ini files.
- FPM config > INI config
- `php-fpm -i` isn't reliable

Remove memory_limit ini files

---

docker/sirius/data/currentUser.json
docker/sirius/openapi.yml
docker/sirius/sirius-config.yaml
service-front/docker-compose.env
service-front/module/Application/src/Services/SiriusApiService.php
service-front/module/Application/test/Unit/Services/SiriusApiServiceTest.php

Instead of bypassing Sirius auth locally, use a fixed endpoint on the mock to ensure it always returns 200.
Fixes ID-535 #patch
Don't check if headers exist first, to more easily enable local development and Cypress tests.

Remove auth bypass

---

docker/sirius/data/currentUser.json
service-api/composer.json
service-api/composer.lock
service-api/docker-compose.env
service-api/module/Application/config/module.config.php
service-api/module/Application/src/Auth/Listener.php
service-api/module/Application/src/Auth/ListenerFactory.php
service-api/module/Application/test/ApplicationTest/Feature/Auth/ListenerTest.php
service-api/module/Application/test/ApplicationTest/Feature/Aws/Secrets/AwsSecretTest.php
service-api/module/Application/test/TestCase.php
service-front/composer.json
service-front/composer.lock
service-front/docker-compose.env
service-front/module/Application/config/module.config.php
service-front/module/Application/src/Auth/JwtGenerator.php
service-front/module/Application/src/Auth/JwtGeneratorFactory.php
service-front/module/Application/src/Factories/OpgApiServiceFactory.php
service-front/module/Application/src/Factories/SiriusApiServiceFactory.php
service-front/module/Application/src/Services/OpgApiService.php
service-front/module/Application/src/Services/SiriusApiService.php
service-front/module/Application/test/Unit/Auth/JwtGeneratorTest.php
service-front/module/Application/test/Unit/Services/OpgApiServiceTest.php
service-front/module/Application/test/Unit/Services/SiriusApiServicePactTest.php
service-front/module/Application/test/Unit/Services/SiriusApiServiceTest.php
service-front/phpunit.xml

Ensure calls to the API are authenticated so a rogue actor could not make requests.
Fixes ID-390 #minor
When making calls to the internal API, generate a JWT and attach it as an Authorization header.
We need to scrape the user's email address of their auth-to-Sirius request to use as the `sub`.
Verify that token in the API, ensuring it has all required fields and they have valid values.
I prefer this method of bypassing the listener, I'll backport it to the frontend too (rather than using an env var)
* N/A
* N/A

Add JWT auth between frontend and API

---

nginx/default.conf.template

Fixes ID-573 #patch
Start with basic default-src header
Zap also wanted us to add "form-action" and "frame-ancestors" because they don't inherit from default-src

Add Content-Security-Policy header to requests

---

service-front/module/Application/src/Controller/DonorFlowController.php
service-front/module/Application/src/Controller/PostOfficeFlowController.php
service-front/module/Application/src/Controller/VouchingFlowController.php

Otherwise the code after the redirect is still executed, and we return a body payload to the browser that is unnecessary.
Fixes ID-574 #patch

Always return redirects immediately

---

e2e-tests/package-lock.json
service-api/Dockerfile
service-front/Dockerfile

- ~~Use the distroless version of imposter, which comes with far fewer dependencies and 231 fewer vulnerabilities~~
- Fewer vulns, but more crits, and has trouble starting up in GHA
- Bump cross-spawn to non-vulnerable version
- Update sqlite to non-vulnerable version
#patch

Security improvements

---

nginx/nginx.conf
service-api/Dockerfile
service-api/module/Application/src/Factories/LoggerFactory.php
service-api/module/Application/src/Services/Logging/OpgFormatter.php
service-api/module/Telemetry/Instrumentation/Logger.php
service-api/module/Telemetry/Propagation/LoggingFormatter.php
service-api/module/Telemetry/Tracer.php
service-front/Dockerfile
service-front/module/Application/src/Factories/LoggerFactory.php
service-front/module/Application/src/Services/Logging/OpgFormatter.php
service-front/module/Telemetry/Instrumentation/Logger.php
service-front/module/Telemetry/Propagation/LoggingFormatter.php
service-front/module/Telemetry/Tracer.php

Log messages in nginx and PHP now include the `trace_id` and `request` fields.
Fixes ID-562 #patch
An OpenTelemetry hook injects the information from the tracecontext propagator. Request information is retrieved from the `Request` service.
The OpgFormatter needed modifications to populate request info and make `trace_id` a top-level field.
* N/A
* N/A
* N/A
* N/A
* I tested on a popup environment

Add `trace_id` and `request` to log messages

---

service-api/module/Application/src/Controller/Factory/HealthcheckControllerFactory.php
service-api/module/Application/src/Controller/HealthcheckController.php
service-api/module/Application/src/Controller/IdentityController.php
service-api/module/Application/src/Controller/KbvController.php
service-api/module/Application/src/Controller/YotiController.php
service-api/module/Application/src/DWP/DwpApi/DwpApiService.php
service-api/module/Application/src/Experian/Crosscore/FraudApi/FraudApiService.php
service-api/module/Application/src/Fixtures/DataWriteHandler.php
service-api/module/Application/test/ApplicationTest/Feature/Controller/KbvControllerTest.php
service-api/module/Application/test/ApplicationTest/Unit/Fixtures/DataWriteHandlerTest.php
service-front/module/Application/src/Controller/CPFlowController.php
service-front/module/Application/src/Controller/DonorFlowController.php
service-front/module/Application/src/Controller/Factory/CPFlowControllerFactory.php
service-front/module/Application/src/Controller/Factory/DonorFlowControllerFactory.php
service-front/module/Application/src/Factories/OpgApiServiceFactory.php
service-front/module/Application/src/Helpers/SiriusDataProcessorHelper.php
service-front/module/Application/src/Services/OpgApiService.php
service-front/module/Application/test/Unit/Helpers/SiriusDataProcessorHelperTest.php
service-front/module/Application/test/Unit/Services/OpgApiServiceTest.php

ensure we log errors wherever we would want to be alerted to an issue and not for any expected behaviour in the application.
fixes [id-560](https://opgtransform.atlassian.net/browse/ID-560) and [id-561](https://opgtransform.atlassian.net/browse/ID-561)
there is a combination of added error logs where they were missing and removing some which were logging behaviour we would expect in the application.
I have also removed a number of redundant try/catch blocks which were obscuring the true cause of errors and resulting in multiple error logs which would make debugging more difficult.

id-560 + id-561 log errors only when needed #minor

---

.github/workflows/build-scan.yml
.github/workflows/test.yml
.github/workflows/workflow-main.yml
docker/hmpo/data/notAuthorisedResponse.json
docker/hmpo/hmpo-config.yaml
docker/hmpo/openapi.yml
service-api/docker-compose.env

deploy new hmpo-mock service in github pipeline
Fixes [ID-586](https://opgtransform.atlassian.net/browse/ID-586)
i unashamedly copied from what was their for the  dwp-mock
[ID-586]: https://opgtransform.atlassian.net/browse/ID-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Id 586 deploy paper id mock

---

.github/workflows/workflow-main.yml

Parameter Store is in a different account to ECR
#patch

Use correct account for SSM OIDC
